version: '3.9'

services:
  user-service:
    build: ./apps/user-service
    ports:
      - "3001:3001"

  product-service:
    build: ./apps/product-service
    ports:
      - "3002:3002"

  order-service:
    build: ./apps/order-service
    ports:
      - "3003:3003"

  rating-service:
    build: ./apps/rating-service
    ports:
      - "3004:3004"

  email-service:
    build: ./apps/email-service
    ports:
      - "3005:3005"

  payment-service:
    build: ./apps/payment-service
    ports:
      - "3006:3006"

  search-service:
    build: ./apps/search-service
    ports:
      - "3007:3007"

  cart-service:
    build: ./apps/cart-service
    ports:
      - "3008:3008"

  admin-service:
    build: ./apps/admin-service
    ports:
      - "3009:3009"

  invoice-service:
    build: ./apps/invoice-service
    ports:
      - "3010:3010"

  analytics-service:
    build: ./apps/analytics-service
    ports:
      - "3011:3011"

  vendor-service:
    build: ./apps/vendor-service
    ports:
      - "3012:3012"

  kong:
    image: kong:3.0
    ports:
      - "8000:8000"     # Public API access
      - "8001:8001"     # Admin API access
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/kong.yml
    volumes:
      - ./kong/kong.yml:/usr/local/kong/kong.yml
    depends_on:
      - user-service
      - product-service
      - order-service
      - rating-service
      - email-service
      - payment-service
      - search-service
      - cart-service
      - admin-service
      - invoice-service
      - analytics-service
      - vendor-service
