_format_version: "3.0"
_transform: true

# ────────────────────────────────
# 🚀 Microservices Configuration
# ────────────────────────────────

services:
  - name: user-service
    url: http://user-service:3000
    routes:
      - name: user-route
        paths: ["/user"]
        plugins:
          - name: cors
            config:
              origins: ["https://your-vercel-app.vercel.app"]
              methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
              headers: ["Authorization", "Content-Type"]
              credentials: true

  - name: product-service
    url: http://product-service:3001
    routes:
      - name: product-route
        paths: ["/product"]
        plugins:
          - name: rate-limiting
            config: { minute: 60 }
          - name: cors
            config: { origins: ["*"] }

  - name: order-service
    url: http://order-service:3002
    routes:
      - name: order-route
        paths: ["/order"]
        plugins:
          - name: cors
            config: { origins: ["*"] }

  - name: rating-service
    url: http://rating-service:3003
    routes:
      - name: rating-route
        paths: ["/rating"]

  - name: email-service
    url: http://email-service:3004
    routes:
      - name: email-route
        paths: ["/email"]

  - name: payment-service
    url: http://payment-service:3005
    routes:
      - name: payment-route
        paths: ["/payment"]

  - name: search-service
    url: http://search-service:3006
    routes:
      - name: search-route
        paths: ["/search"]
        plugins:
          - name: rate-limiting
            config: { minute: 100 }
          - name: cors
            config: { origins: ["*"] }

  - name: cart-service
    url: http://cart-service:3007
    routes:
      - name: cart-route
        paths: ["/cart"]
        plugins:
          - name: rate-limiting
            config: { minute: 30 }
          - name: cors
            config: { origins: ["*"] }

  - name: admin-service
    url: http://admin-service:3008
    routes:
      - name: admin-route
        paths: ["/admin"]
        plugins:
          - name: jwt
          - name: cors
            config:
              origins: ["https://your-vercel-app.vercel.app"]

  - name: invoice-service
    url: http://invoice-service:3009
    routes:
      - name: invoice-route
        paths: ["/invoice"]
        plugins:
          - name: cors
            config: { origins: ["*"] }

  - name: analytics-service
    url: http://analytics-service:3010
    routes:
      - name: analytics-route
        paths: ["/analytics"]

  - name: vendor-service
    url: http://vendor-service:3011
    routes:
      - name: vendor-route
        paths: ["/vendor"]
        plugins:
          - name: jwt
          - name: cors
            config:
              origins: ["https://your-vercel-app.vercel.app"]

# ────────────────────────────────
# 👤 Consumers (Clients using JWT)
# ────────────────────────────────

consumers:
  - username: admin-app
    custom_id: admin-001
    jwt_secrets:
      - key: admin-key
        secret: admin-secret

  - username: vendor-app
    custom_id: vendor-001
    jwt_secrets:
      - key: vendor-key
        secret: vendor-secret
