replicaCount: 1

image:
  repository: your-dockerhub/search-service
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: 'nginx'
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  hosts:
    - host: api.localhost
      paths:
        - path: /api/search/(.*)
          pathType: ImplementationSpecific

resources: {}
env: {}
