helmDefaults:
  wait: true
  timeout: 600
  createNamespace: true

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: kong
    url: https://charts.konghq.com
  - name: falcosecurity
    url: https://falcosecurity.github.io/charts

releases:
  # === INFRA: DATABASES ===
  - name: postgres
    namespace: database
    chart: bitnami/postgresql
    values:
      - ../helm/database/postgres-values.yaml

  - name: redis
    namespace: cache
    chart: bitnami/redis
    values:
      - ../helm/database/redis-values.yaml

  - name: kafka
    namespace: messaging
    chart: bitnami/kafka
    values:
      - ../helm/database/kafka-values.yaml

  - name: minio
    namespace: storage
    chart: ../helm/database/minio
    values:
      - ../helm/database/minio/values.yaml

  # === INGRESS CONTROLLERS ===
  - name: nginx-ingress
    namespace: ingress
    chart: bitnami/nginx-ingress-controller
    values:
      - ../helm/ingress/nginx/values.yaml

  - name: kong
    namespace: kong
    chart: kong/kong
    values:
      - ../helm/ingress/kong/values.yaml

  # === MONITORING STACK ===
  - name: prometheus
    namespace: observability
    chart: ../helm/monitoring/prometheus
    values:
      - ../helm/monitoring/prometheus/values.yaml

  - name: grafana
    namespace: observability
    chart: ../helm/monitoring/grafana
    values:
      - ../helm/monitoring/grafana/values.yaml

  - name: loki
    namespace: observability
    chart: ../helm/monitoring/loki
    values:
      - ../helm/monitoring/loki/values.yaml

  - name: jaeger
    namespace: observability
    chart: ../helm/monitoring/jaeger
    values:
      - ../helm/monitoring/jaeger/values.yaml

  # === SECURITY STACK ===
  - name: falco
    namespace: security
    chart: falcosecurity/falco
    values:
      - ../helm/security/falco/values.yaml

  - name: trivy
    namespace: security
    chart: ../helm/security/trivy
    values:
      - ../helm/security/trivy/values.yaml

  # === NETWORK ===
  - name: calico
    namespace: network
    chart: ../helm/network/calico
    values:
      - ../helm/network/calico/values.yaml

  # === MICROSERVICES ===
  - name: user-service
    namespace: user
    chart: ../helm/microservices/user-service
    values:
      - ../helm/microservices/user-service/values.yaml

  - name: product-service
    namespace: product
    chart: ../helm/microservices/product-service
    values:
      - ../helm/microservices/product-service/values.yaml

  - name: order-service
    namespace: order
    chart: ../helm/microservices/order-service
    values:
      - ../helm/microservices/order-service/values.yaml

  - name: payment-service
    namespace: payment
    chart: ../helm/microservices/payment-service
    values:
      - ../helm/microservices/payment-service/values.yaml

  - name: rating-service
    namespace: rating
    chart: ../helm/microservices/rating-service
    values:
      - ../helm/microservices/rating-service/values.yaml

  - name: email-service
    namespace: email
    chart: ../helm/microservices/email-service
    values:
      - ../helm/microservices/email-service/values.yaml

  - name: cart-service
    namespace: cart
    chart: ../helm/microservices/cart-service
    values:
      - ../helm/microservices/cart-service/values.yaml

  - name: search-service
    namespace: search
    chart: ../helm/microservices/search-service
    values:
      - ../helm/microservices/search-service/values.yaml
